baseURL = "https://rose-m.github.io"
languageCode = "en-us"
title = "Michael Rose"
theme = "hugo-cactus-theme"

[params]
    name = "Michael Rose"
    description = "This only represents my personal opinion"
    bio = "Programmer & Play-Kid"
